// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVoPZ9qKpMaBVGdT1uiCbMjF7Zlxu3fns',
    appId: '1:60493351906:web:6c912d98e36cd8d458c7bb',
    messagingSenderId: '60493351906',
    projectId: 'doctolo',
    authDomain: 'doctolo.firebaseapp.com',
    storageBucket: 'doctolo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPjdn_C5PgOx-9DrlGc9DVzEMg8WJcZfs',
    appId: '1:60493351906:android:9661a0ad294f740758c7bb',
    messagingSenderId: '60493351906',
    projectId: 'doctolo',
    storageBucket: 'doctolo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1EGklP_S77eiFYfpDhbieoxNN-di60iQ',
    appId: '1:60493351906:ios:e47da9beaf088bc758c7bb',
    messagingSenderId: '60493351906',
    projectId: 'doctolo',
    storageBucket: 'doctolo.firebasestorage.app',
    iosBundleId: 'com.juleskouadio.doctolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1EGklP_S77eiFYfpDhbieoxNN-di60iQ',
    appId: '1:60493351906:ios:e47da9beaf088bc758c7bb',
    messagingSenderId: '60493351906',
    projectId: 'doctolo',
    storageBucket: 'doctolo.firebasestorage.app',
    iosBundleId: 'com.juleskouadio.doctolo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVoPZ9qKpMaBVGdT1uiCbMjF7Zlxu3fns',
    appId: '1:60493351906:web:9005ad7145a5193d58c7bb',
    messagingSenderId: '60493351906',
    projectId: 'doctolo',
    authDomain: 'doctolo.firebaseapp.com',
    storageBucket: 'doctolo.firebasestorage.app',
  );

}